DECLARE @LOL TABLE (
	 ID		integer	NOT NULL
	,Val	integer	NOT NULL
)
;

INSERT @LOL
SELECT 1, 1 UNION ALL SELECT 1, 2 UNION ALL SELECT 1, 4 UNION ALL
SELECT 2, 7 UNION ALL SELECT 2, 9 UNION ALL SELECT 2, 10
;

SELECT *
FROM @LOL
ORDER BY ID, Val
;

;WITH x AS (
	SELECT *, NextVal = LEAD(Val, 1, NULL) OVER (PARTITION BY ID ORDER BY Val)
	FROM @LOL
)
SELECT *
FROM x
WHERE (NextVal - Val > 1) OR NextVal IS NULL
;
